In [ ]:
dosyam = "ornek.txt"

with open(dosyam,"w",encoding="utf-8") as file:
  file.write(" merhaba dosya okuma.\npython oop tabanlı bir dildir\n derslerbayaiyi")


In [ ]:
with open("ornek.txt","r") as file:
  content = file.read()
  print(content)

 merhaba dosya okuma.
python oop tabanlı bir dildir
 derslerbayaiyi


In [ ]:
with open("ornek.txt","r") as file:
  content = file.readlines()
  print(f"dosyadaki satır sayısı : {len(content)}")


dosyadaki satır sayısı : 3


In [ ]:
with open("ornek.txt","r") as file:
  content = file.read()
  print(f"dosyadaki karakter sayısı : {len(content)}")

dosyadaki karakter sayısı : 67


In [ ]:
arama = input("aramak istediğin kelime ")
with open("ornek.txt","r") as file:
  content = file.read()
  kelimesayı = content.count(arama) + 0
  print(f" kelimenin dosyadaki  sayısı : {kelimesayı}")


aramak istediğin kelime b
 kelimenin dosyadaki  sayısı : 4


In [ ]:
with open("ornek.txt","r") as file:
  content = file.read()
  enuzunkelime = max(content.split(),key=len)
  print(f"enuzun kelime : {enuzunkelime}")

enuzun kelime : derslerbayaiyi


In [ ]:
with open("ornek.txt","r") as file:
  content = file.read()
  tersten = content[::-1]
  print(f"tersten tüm satırlar : {tersten}")

tersten tüm satırlar : iyiayabrelsred 
ridlid rib ılnabat poo nohtyp
.amuko aysod abahrem 


In [ ]:
import shutil

ilk= "ornek.txt"
ikinci = "ornek2BUYUK.txt"

shutil.copy(ilk,ikinci)

with open("ornek2BUYUK.txt","r") as file:
  content = file.read()
  print (content)


 merhaba dosya okuma.
python oop tabanlı bir dildir
 derslerbayaiyi


In [ ]:
with open("ornek2BUYUK.txt","r") as file:
  content = file.read()
  buyukharf = content.upper()
  print(f"büyük harfli hali : {buyukharf}")

büyük harfli hali :  MERHABA DOSYA OKUMA.
PYTHON OOP TABANLI BIR DILDIR
 DERSLERBAYAIYI


In [ ]:
satir_numarasi = int(input("Okumak istediğiniz satır numarasını girin: "))

with open("ornek.txt", "r") as dosya:
  satirlar = dosya.readlines()

if satir_numarasi <= len(satirlar) and satir_numarasi >0:
  print(satirlar[satir_numarasi - 1])
else:
  print("Geçersiz satır numarası.")

Okumak istediğiniz satır numarasını girin: 4
Geçersiz satır numarası.


In [ ]:
from collections import Counter
with open("ornek.txt", "r") as dosya:
  satirlar = dosya.read().split()
  sayac = Counter(satirlar)
  print(f"kullanılan kelime: {sayac}")

kullanılan kelime: Counter({'merhaba': 1, 'dosya': 1, 'okuma.': 1, 'python': 1, 'oop': 1, 'tabanlı': 1, 'bir': 1, 'dildir': 1, 'derslerbayaiyi': 1})


In [ ]:
import csv

dosya = "ornek.csv"

veri= [
    ['ad','yas','sınıf'],
    ['berat','16','program'],
    ['elif','15','matematik'],
    ['deniz','14','fizik']
]

with open(dosya,'w',newline='',encoding='utf-8') as file:
  writer = csv.writer(file)
  writer.writerows(veri)

with open(dosya,'r',newline='',encoding='utf-8') as file:
  reader = csv.reader(file)
  for row in reader:
    print(row)

['ad', 'yas', 'sınıf']
['berat', '16', 'program']
['elif', '15', 'matematik']
['deniz', '14', 'fizik']


In [ ]:
with open("ornek.txt", "r") as dosya:
  toplamsatır=0
  toplamkelime=0
  en_uzun_satır = ""
  for line in dosya:
    toplamsatır+=1

    toplamkelime+=len(line.split())
    if len(line)>len(en_uzun_satır):
      enuzunsatır=line.strip()

print(f"Toplam Satır Sayısı: {toplamsatır}")
print(f"Toplam Kelime Sayısı: {toplamkelime}")
print(f"En Uzun Satır: {enuzunsatır}")


Toplam Satır Sayısı: 3
Toplam Kelime Sayısı: 9
En Uzun Satır: derslerbayaiyi


In [ ]:
import numpy as np

data = [[1,2,3],[3,4,5],[6,7,8]]

arayone = np.array(data)

print(arayone)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

np.zeros(100)

np.ones(100)

np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np

rastgele = np.arange(50,101)

print(rastgele)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [ ]:
sifirlar = np.zeros((100,100), dtype = "int")
sifirlar

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.ones(100,int)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
rast = np.random.randint(0,100,5)
rast

array([37, 18, 66, 82, 87])

In [ ]:
rast = np.random.rand(1)

print ( rast)

[0.13579773]


In [ ]:
rast = np.random.randn(1)
rast

array([-1.64136996])

In [ ]:
np.arange(0,256)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
data1.reshape(15,15)

AttributeError: 'list' object has no attribute 'reshape'